sudo: required
# Necesita docker
services:
  - docker
before_install:
  # Se utiliza el Dockerfile.dev ya que el Dockerfile esta pensado para produccion arrancando Nginx. Importante localizacion del dockerfile y context
  - docker build -t kike/docker-react-myself-test -f ./client/Dockerfile.dev ./client
# Primera test running section: cualquier script que salga de aqui otro que 0 es considerado un error
script:
  #- docker run kike/docker-react-myself-test npm test -- --coverage
# Si todo ha ido bien en los test, se tiene que ir configurando los build
# Se crean las imagenes de los 4 proyectos y se suben a docker hub
after_success:
  #- docker build -t kike/multi-client ./client
  #- docker build -t kike/multi-nginx ./nginx
  #- docker build -t kike/multi-server ./server
  #- docker build -t kike/multi-worker ./worker
  # Primero se tiene que login en el docker cli

  # Se coge las imagenes y se ponen un docker hub
